name: Release

on:
  push:
    tags:
      - "v*"   # e.g. v0.1.0, v1.2.3
  workflow_dispatch: {}  # allow manual runs too

permissions:
  contents: write  # REQUIRED to create releases & upload assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Some repos need this if gradlew lost its +x bit in git
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the distributable Fabric jar (Loom outputs to build/libs via remapJar)
      - name: Build (remapJar)
        run: ./gradlew --stacktrace --no-daemon clean remapJar

      # Optionally also build sources/javadoc jars if you want
      # - run: ./gradlew sourcesJar javadocJar

      # Grab the version from the tag (e.g. v1.2.3 -> 1.2.3)
      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      # Create the GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Skydrunk ${{ steps.vars.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
